# Generated by Django 5.2.17 on 2026-10-03 22:09

import core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Se genera solo si lo dejas vacío.', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, upload_to='categorias/', validators=[core.validators.validar_imagen])),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Se genera solo si lo dejas vacío.', max_length=170, unique=True)),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='SKU')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio de oferta')),
                ('oferta_inicio', models.DateTimeField(blank=True, null=True, verbose_name='inicio de la oferta')),
                ('oferta_fin', models.DateTimeField(blank=True, null=True, verbose_name='fin de la oferta')),
                ('stock_almacen', models.PositiveIntegerField(default=0, verbose_name='stock en almacén')),
                ('stock_reservado', models.PositiveIntegerField(default=0, editable=False, help_text='Unidades apartadas por pedidos sin entregar. Lo maneja el sistema.', verbose_name='stock reservado')),
                ('destacado', models.BooleanField(default=False)),
                ('nuevo', models.BooleanField(default=False, help_text='Márcalo para mostrarlo siempre como nuevo.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='JPG, PNG o WebP de hasta 5 MB. Se ajusta a 1200 px y se guarda en WebP.', upload_to='productos/%Y/%m/', validators=[core.validators.validar_imagen])),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('principal', models.BooleanField(default=False, help_text='Es la foto que se ve en las tarjetas.')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'foto de producto',
                'verbose_name_plural': 'fotos de producto',
                'ordering': ['-principal', 'orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', '-creado'], name='producto_activo_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'destacado'], name='producto_activo_destacado_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='producto_categoria_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='producto_precio_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gt', 0)), name='producto_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_oferta__isnull', True), models.Q(('precio_oferta__gt', 0), ('precio_oferta__lt', models.F('precio'))), _connector='OR'), name='producto_oferta_menor_que_precio'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reservado__lte', models.F('stock_almacen'))), name='producto_reservado_no_supera_almacen'),
        ),
    ]
