# Generated by Django 5.2.17 on 2026-10-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_busqueda_sin_tildes'),
        ('tiendas', '0001_tienda_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tiendas.tienda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Código del producto. No se repite dentro de la tienda.', max_length=40, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera solo si lo dejas vacío.', max_length=170),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tienda', 'activo', '-creado'], name='producto_tienda_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('tienda', 'sku'), name='producto_sku_unico_por_tienda', violation_error_message='Ya tienes un producto con ese SKU.'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('tienda', 'slug'), name='producto_slug_unico_por_tienda', violation_error_message='Ya tienes un producto con ese slug.'),
        ),
    ]
