# Generated by Django 5.2.17 on 2026-10-07 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_asignar_tienda'),
        ('tiendas', '0002_tienda_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tiendas.tienda'),
        ),
    ]
