# Generated by Django 5.2.17 on 2026-10-09 03:41

import core.archivos
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_tienda_obligatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=core.archivos.NombreUnico('categorias'), validators=[core.validators.validar_imagen]),
        ),
    ]
