# Generated by Django 5.2.17 on 2026-10-03 22:08

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Multimix RD', max_length=80, verbose_name='nombre de la tienda')),
                ('logo', models.ImageField(blank=True, help_text='Si no subes un logo se muestra el nombre en texto.', upload_to='tienda/', validators=[core.validators.validar_imagen])),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('horario', models.CharField(blank=True, help_text='Ej.: Lun a Sáb, 9:00 a.m. a 6:00 p.m.', max_length=150)),
                ('whatsapp', models.CharField(blank=True, help_text='Solo dígitos, con código de país. Ej.: 18095551234', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Escribe solo dígitos, con el código de país. Ejemplo: 18095551234')], verbose_name='número de WhatsApp')),
                ('direccion_tienda', models.CharField(blank=True, help_text='Se muestra a quien elige recoger en tienda.', max_length=255, verbose_name='dirección de la tienda')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('banner_titulo', models.CharField(default='Todo lo que buscas, en un solo lugar', max_length=120, verbose_name='título del banner')),
                ('banner_subtitulo', models.CharField(blank=True, default='Productos de todas las categorías con entrega en todo el país.', max_length=220, verbose_name='subtítulo del banner')),
                ('banner_texto_boton', models.CharField(default='Ver catálogo', max_length=40, verbose_name='texto del botón del banner')),
                ('banner_imagen', models.ImageField(blank=True, upload_to='tienda/', validators=[core.validators.validar_imagen], verbose_name='imagen del banner')),
                ('dias_producto_nuevo', models.PositiveSmallIntegerField(default=30, help_text='Días desde su creación en que un producto se muestra como nuevo.', verbose_name='días como producto nuevo')),
                ('umbral_stock_bajo', models.PositiveSmallIntegerField(default=5, help_text='Con esta cantidad o menos se avisa que queda poco.', verbose_name='umbral de stock bajo')),
                ('horas_vencimiento_pedido', models.PositiveSmallIntegerField(default=48, validators=[django.core.validators.MinValueValidator(1)], verbose_name='horas para vencer pedidos pendientes')),
                ('mostrar_cantidad_exacta', models.BooleanField(default=False, help_text='Si está apagado solo se muestra "Disponible" o "Quedan X" cuando hay poco.', verbose_name='mostrar la cantidad exacta disponible')),
                ('permitir_contra_entrega', models.BooleanField(default=False, verbose_name='permitir efectivo contra entrega')),
            ],
            options={
                'verbose_name': 'configuración de la tienda',
                'verbose_name_plural': 'configuración de la tienda',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=80)),
                ('tipo_cuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], default='ahorros', max_length=10, verbose_name='tipo de cuenta')),
                ('numero', models.CharField(max_length=30, verbose_name='número de cuenta')),
                ('titular', models.CharField(max_length=120)),
                ('cedula_rnc', models.CharField(blank=True, max_length=20, verbose_name='cédula o RNC')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
                'ordering': ['orden', 'banco'],
                'constraints': [models.UniqueConstraint(fields=('banco', 'numero'), name='cuenta_banco_numero_unica')],
            },
        ),
    ]
