# Generated by Django 5.2.17 on 2026-10-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_textos_de_marca'),
        ('tiendas', '0001_tienda_inicial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuentabancaria',
            name='cuenta_banco_numero_unica',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='tiendas.tienda'),
        ),
        migrations.AddConstraint(
            model_name='cuentabancaria',
            constraint=models.UniqueConstraint(fields=('tienda', 'banco', 'numero'), name='cuenta_unica_por_tienda', violation_error_message='Ya registraste esa cuenta de ese banco.'),
        ),
    ]
