# Generated by Django 5.2.17 on 2026-10-07 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asignar_tienda'),
        ('tiendas', '0002_tienda_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciontienda',
            options={'verbose_name': 'configuración general', 'verbose_name_plural': 'configuración general'},
        ),
        migrations.RemoveField(
            model_name='configuraciontienda',
            name='direccion_tienda',
        ),
        migrations.RemoveField(
            model_name='configuraciontienda',
            name='permitir_contra_entrega',
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='nombre',
            field=models.CharField(default='Multimix RD', max_length=80, verbose_name='nombre del sitio'),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='tiendas.tienda'),
        ),
    ]
