# Generated by Django 5.2.17 on 2026-10-09 03:19

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_portada_sin_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontienda',
            name='descripcion',
            field=models.CharField(blank=True, default='Tiendas de emprendedores en un solo lugar. Compra directo a cada tienda por WhatsApp.', help_text='Frase corta sobre el sitio: sale al pie de la portada y en los buscadores como Google.', max_length=220, verbose_name='descripción del sitio'),
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='logo',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP de hasta 5 MB. Si no subes un logo se muestra el símbolo con el nombre.', upload_to='tienda/', validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='configuraciontienda',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej.: 829-555-1234. A los números dominicanos se les agrega solo el 1 del código de país.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Escribe el número completo, con su código de área. Ejemplo: 829-555-1234')], verbose_name='número de WhatsApp'),
        ),
    ]
