# Generated by Django 5.2.17 on 2026-10-09 03:41

import core.archivos
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_descripcion_y_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontienda',
            name='logo',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP de hasta 5 MB. Si no subes un logo se muestra el símbolo con el nombre.', upload_to=core.archivos.NombreUnico('tienda'), validators=[core.validators.validar_imagen]),
        ),
    ]
