# Generated by Django 5.2.17 on 2026-10-03 22:14

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaPedido',
            fields=[
                ('anio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'secuencia de pedidos',
                'verbose_name_plural': 'secuencias de pedidos',
            },
        ),
        migrations.CreateModel(
            name='ZonaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'zona de envío',
                'verbose_name_plural': 'zonas de envío',
                'ordering': ['orden', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tarifa__gte', 0)), name='zona_tarifa_no_negativa')],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=10, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('metodo_entrega', models.CharField(choices=[('recoger', 'Recoger en tienda'), ('envio', 'Envío a domicilio')], max_length=10, verbose_name='método de entrega')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='referencia de la dirección')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('efectivo_recoger', 'Efectivo al recoger'), ('contra_entrega', 'Efectivo contra entrega')], max_length=20, verbose_name='método de pago')),
                ('transferencia_realizada', models.BooleanField(default=False, verbose_name='el cliente dice que ya transfirió')),
                ('referencia_transferencia', models.CharField(blank=True, max_length=60, verbose_name='referencia de la transferencia')),
                ('codigo_cupon', models.CharField(blank=True, max_length=30, verbose_name='código de cupón aplicado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='costo de envío')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('listo', 'Listo para recoger'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('notas_cliente', models.TextField(blank=True, verbose_name='notas del cliente')),
                ('notas_internas', models.TextField(blank=True, help_text='Solo se ven en el panel.', verbose_name='notas internas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='fecha de pago')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('stock_descontado', models.BooleanField(default=False, editable=False, verbose_name='stock ya descontado')),
                ('ip', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='IP del cliente')),
                ('cupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='promociones.cupon', verbose_name='cupón')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.zonaenvio', verbose_name='zona de envío')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150, verbose_name='producto (al comprar)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario (al comprar)')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'producto del pedido',
                'verbose_name_plural': 'productos del pedido',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_cantidad_positiva'), models.UniqueConstraint(fields=('pedido', 'producto'), name='detalle_producto_unico_por_pedido')],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', '-creado'], name='pedido_estado_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-creado'], name='pedido_creado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_pago'], name='pedido_fecha_pago_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['telefono'], name='pedido_telefono_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['ip', '-creado'], name='pedido_ip_creado_idx'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('metodo_entrega', 'recoger'), ('zona__isnull', False), _connector='OR'), name='pedido_envio_requiere_zona'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metodo_pago', 'efectivo_recoger'), _negated=True), ('metodo_entrega', 'recoger'), _connector='OR'), name='pedido_efectivo_recoger_solo_en_tienda'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('costo_envio__gte', 0), ('total__gte', 0)), name='pedido_montos_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.CheckConstraint(condition=models.Q(('descuento__gte', 0), ('descuento__lte', models.F('subtotal'))), name='pedido_descuento_no_supera_subtotal'),
        ),
    ]
