# Generated by Django 5.2.17 on 2026-10-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('promociones', '0002_tienda_inicial'),
        ('tiendas', '0001_tienda_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'secuencia de pedidos',
                'verbose_name_plural': 'secuencias de pedidos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='zonaenvio',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonas_envio', to='tiendas.tienda'),
        ),
        migrations.AlterField(
            model_name='zonaenvio',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['tienda', '-creado'], name='pedido_tienda_creado_idx'),
        ),
        migrations.AddConstraint(
            model_name='zonaenvio',
            constraint=models.UniqueConstraint(fields=('tienda', 'nombre'), name='zona_nombre_unico_por_tienda', violation_error_message='Ya tienes una zona con ese nombre.'),
        ),
        migrations.AddField(
            model_name='secuenciatienda',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias', to='tiendas.tienda'),
        ),
        migrations.AddConstraint(
            model_name='secuenciatienda',
            constraint=models.UniqueConstraint(fields=('tienda', 'anio'), name='secuencia_unica_por_tienda_y_anio'),
        ),
    ]
