# Generated by Django 5.2.17 on 2026-10-07 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_asignar_tienda'),
        ('tiendas', '0002_tienda_principal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecuenciaPedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tienda',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='tiendas.tienda'),
        ),
        migrations.AlterField(
            model_name='zonaenvio',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_envio', to='tiendas.tienda'),
        ),
    ]
