# Generated by Django 5.2.17 on 2026-10-03 22:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Se guarda en mayúsculas.', max_length=30, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo')], default='porcentaje', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje (1 a 100) o monto en RD$, según el tipo.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('compra_minima', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='compra mínima')),
                ('vigente_desde', models.DateTimeField(blank=True, null=True)),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Vacío = ilimitado.', null=True, verbose_name='usos máximos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, editable=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['codigo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='cupon_valor_positivo'), models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'porcentaje'), _negated=True), ('valor__lte', 100), _connector='OR'), name='cupon_porcentaje_maximo_100')],
            },
        ),
    ]
