# Generated by Django 5.2.17 on 2026-10-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
        ('tiendas', '0001_tienda_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='tiendas.tienda'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='codigo',
            field=models.CharField(help_text='Se guarda en mayúsculas.', max_length=30, verbose_name='código'),
        ),
        migrations.AddConstraint(
            model_name='cupon',
            constraint=models.UniqueConstraint(fields=('tienda', 'codigo'), name='cupon_codigo_unico_por_tienda', violation_error_message='Ya tienes un cupón con ese código.'),
        ),
    ]
