# Generated by Django 5.2.17 on 2026-10-07 16:08

import core.validators
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Parte del enlace de la tienda: /tienda/<esto>/. Se genera sola si la dejas vacía.', max_length=60, unique=True, verbose_name='dirección web')),
                ('prefijo', models.CharField(blank=True, help_text='Con él empiezan sus números de pedido (FIT-2026-00001). Vacío = se toma del nombre. No se puede cambiar después.', max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,5}$', 'Usa de 2 a 5 letras mayúsculas o números, sin espacios. Ejemplo: FIT')], verbose_name='prefijo de pedidos')),
                ('activa', models.BooleanField(default=True, help_text='Si la apagas, la tienda y sus productos dejan de verse en el sitio.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Posición en el directorio de tiendas.')),
                ('logo', models.ImageField(blank=True, help_text='Si no subes un logo se muestra el nombre en texto.', upload_to='tiendas/', validators=[core.validators.validar_imagen])),
                ('banner_titulo', models.CharField(blank=True, help_text='Vacío = se muestra el nombre de la tienda.', max_length=120, verbose_name='título del banner')),
                ('banner_subtitulo', models.CharField(blank=True, help_text='Frase corta que describe la tienda. También se ve en el directorio de tiendas.', max_length=220, verbose_name='subtítulo del banner')),
                ('banner_texto_boton', models.CharField(default='Ver catálogo', max_length=40, verbose_name='texto del botón del banner')),
                ('banner_imagen', models.ImageField(blank=True, upload_to='tiendas/', validators=[core.validators.validar_imagen], verbose_name='imagen del banner')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('horario', models.CharField(blank=True, help_text='Ej.: Lun a Sáb, 9:00 a.m. a 6:00 p.m.', max_length=150)),
                ('whatsapp', models.CharField(blank=True, help_text='Aquí llegan los pedidos. Solo dígitos, con código de país. Ej.: 18095551234', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Escribe solo dígitos, con el código de país. Ejemplo: 18095551234')], verbose_name='número de WhatsApp')),
                ('direccion_tienda', models.CharField(blank=True, help_text='Se muestra a quien elige recoger su pedido.', max_length=255, verbose_name='dirección para recoger')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('permitir_contra_entrega', models.BooleanField(default=False, verbose_name='permitir efectivo contra entrega')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Usuarios que administran esta tienda. Al guardar reciben acceso al panel y solo ven lo de sus tiendas.', related_name='tiendas', to=settings.AUTH_USER_MODEL, verbose_name='vendedores')),
            ],
            options={
                'verbose_name': 'tienda',
                'verbose_name_plural': 'tiendas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
