# Generated by Django 5.2.17 on 2026-10-09 03:19

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_tienda_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='banner_imagen',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP de hasta 5 MB. Es el fondo del banner de la tienda y de su tarjeta en la portada.', upload_to='tiendas/', validators=[core.validators.validar_imagen], verbose_name='imagen del banner'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, help_text='JPG, PNG o WebP de hasta 5 MB. Si no subes un logo se muestra el nombre en texto.', upload_to='tiendas/', validators=[core.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Aquí llegan los pedidos. Ej.: 829-555-1234. A los números dominicanos se les agrega solo el 1 del código de país.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', 'Escribe el número completo, con su código de área. Ejemplo: 829-555-1234')], verbose_name='número de WhatsApp'),
        ),
    ]
